version: '3.8'

services:
  postgres:
    container_name: hero_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heroes
    ports:
      - "5432:5432"